export type LevelId = "a1" | "a2" | "b1";

export type WordItem = {
  word: string;
  meaning: string;
  type: string;
  example: string;
  translation: string;
};

export const levelNames: Record<LevelId, string> = {
  a1: "DELE A1 基础词汇",
  a2: "DELE A2 初级词汇",
  b1: "DELE B1 中级词汇",
};

export const wordBank: Record<LevelId, WordItem[]> = {
  a1: [
    {
      word: "hola",
      meaning: "你好",
      type: "interj.",
      example: "Hola, ¿cómo estás?",
      translation: "你好，你怎么样？",
    },
    {
      word: "gracias",
      meaning: "谢谢",
      type: "interj.",
      example: "Muchas gracias por tu ayuda.",
      translation: "非常感谢你的帮助。",
    },
    {
      word: "por favor",
      meaning: "请",
      type: "loc.",
      example: "Un café, por favor.",
      translation: "请给我一杯咖啡。",
    },
    {
      word: "perdón",
      meaning: "对不起；不好意思",
      type: "interj.",
      example: "Perdón, no entiendo.",
      translation: "不好意思，我不明白。",
    },
    {
      word: "sí",
      meaning: "是；对",
      type: "adv.",
      example: "Sí, quiero aprender español.",
      translation: "是的，我想学习西班牙语。",
    },
    {
      word: "no",
      meaning: "不；没有",
      type: "adv.",
      example: "No tengo tiempo hoy.",
      translation: "我今天没有时间。",
    },
    {
      word: "casa",
      meaning: "房子；家",
      type: "n. f.",
      example: "Mi casa está cerca de la escuela.",
      translation: "我家在学校附近。",
    },
    {
      word: "escuela",
      meaning: "学校",
      type: "n. f.",
      example: "La escuela está abierta.",
      translation: "学校开着。",
    },
    {
      word: "amigo",
      meaning: "朋友",
      type: "n. m.",
      example: "Mi amigo vive en Madrid.",
      translation: "我的朋友住在马德里。",
    },
    {
      word: "familia",
      meaning: "家庭；家人",
      type: "n. f.",
      example: "Mi familia es muy grande.",
      translation: "我的家人很多。",
    },
    {
      word: "agua",
      meaning: "水",
      type: "n. f.",
      example: "Quiero un vaso de agua.",
      translation: "我想要一杯水。",
    },
    {
      word: "café",
      meaning: "咖啡",
      type: "n. m.",
      example: "Tomo café por la mañana.",
      translation: "我早上喝咖啡。",
    },
    {
      word: "pan",
      meaning: "面包",
      type: "n. m.",
      example: "Compro pan en la tienda.",
      translation: "我在商店买面包。",
    },
    {
      word: "libro",
      meaning: "书",
      type: "n. m.",
      example: "Leo un libro en español.",
      translation: "我读一本西班牙语书。",
    },
    {
      word: "día",
      meaning: "天；日子",
      type: "n. m.",
      example: "Hoy es un buen día.",
      translation: "今天是个好日子。",
    },
    {
      word: "noche",
      meaning: "夜晚",
      type: "n. f.",
      example: "Buenas noches.",
      translation: "晚安。",
    },
    {
      word: "comer",
      meaning: "吃",
      type: "v.",
      example: "Vamos a comer juntos.",
      translation: "我们一起吃饭吧。",
    },
    {
      word: "beber",
      meaning: "喝",
      type: "v.",
      example: "Quiero beber agua.",
      translation: "我想喝水。",
    },
    {
      word: "hablar",
      meaning: "说话；交谈",
      type: "v.",
      example: "Quiero hablar contigo.",
      translation: "我想和你说话。",
    },
    {
      word: "vivir",
      meaning: "居住；生活",
      type: "v.",
      example: "Vivo en China.",
      translation: "我住在中国。",
    },
  ],

  a2: [
    {
      word: "viajar",
      meaning: "旅行",
      type: "v.",
      example: "Me gusta viajar en verano.",
      translation: "我喜欢在夏天旅行。",
    },
    {
      word: "trabajar",
      meaning: "工作",
      type: "v.",
      example: "Trabajo en una oficina.",
      translation: "我在办公室工作。",
    },
    {
      word: "aprender",
      meaning: "学习",
      type: "v.",
      example: "Aprendo español todos los días.",
      translation: "我每天学习西班牙语。",
    },
    {
      word: "entender",
      meaning: "理解；明白",
      type: "v.",
      example: "No entiendo esta palabra.",
      translation: "我不明白这个单词。",
    },
    {
      word: "comprar",
      meaning: "买",
      type: "v.",
      example: "Quiero comprar una chaqueta.",
      translation: "我想买一件夹克。",
    },
    {
      word: "vender",
      meaning: "卖",
      type: "v.",
      example: "Esta tienda vende frutas.",
      translation: "这家商店卖水果。",
    },
    {
      word: "ciudad",
      meaning: "城市",
      type: "n. f.",
      example: "Madrid es una ciudad grande.",
      translation: "马德里是一座大城市。",
    },
    {
      word: "calle",
      meaning: "街道",
      type: "n. f.",
      example: "La calle es muy tranquila.",
      translation: "这条街很安静。",
    },
    {
      word: "tienda",
      meaning: "商店",
      type: "n. f.",
      example: "Voy a la tienda.",
      translation: "我去商店。",
    },
    {
      word: "precio",
      meaning: "价格",
      type: "n. m.",
      example: "El precio es muy alto.",
      translation: "价格很高。",
    },
    {
      word: "dinero",
      meaning: "钱",
      type: "n. m.",
      example: "No tengo mucho dinero.",
      translation: "我没有很多钱。",
    },
    {
      word: "tiempo",
      meaning: "时间；天气",
      type: "n. m.",
      example: "No tengo tiempo ahora.",
      translation: "我现在没有时间。",
    },
    {
      word: "ayer",
      meaning: "昨天",
      type: "adv.",
      example: "Ayer estudié español.",
      translation: "昨天我学习了西班牙语。",
    },
    {
      word: "mañana",
      meaning: "明天；早晨",
      type: "n. f. / adv.",
      example: "Mañana voy al trabajo.",
      translation: "明天我去工作。",
    },
    {
      word: "cansado",
      meaning: "累的",
      type: "adj.",
      example: "Estoy cansado después del trabajo.",
      translation: "下班后我很累。",
    },
    {
      word: "contento",
      meaning: "高兴的",
      type: "adj.",
      example: "Estoy contento con mi progreso.",
      translation: "我对自己的进步很高兴。",
    },
  ],

  b1: [
    {
      word: "aunque",
      meaning: "虽然；即使",
      type: "conj.",
      example: "Aunque llueve, voy a salir.",
      translation: "虽然下雨，我还是要出门。",
    },
    {
      word: "sin embargo",
      meaning: "然而；不过",
      type: "loc.",
      example: "Es difícil; sin embargo, quiero intentarlo.",
      translation: "这很难，不过我想试试。",
    },
    {
      word: "por eso",
      meaning: "因此；所以",
      type: "loc.",
      example: "Estoy cansado, por eso voy a descansar.",
      translation: "我很累，所以我要休息。",
    },
    {
      word: "lograr",
      meaning: "实现；达成",
      type: "v.",
      example: "Quiero lograr mi objetivo.",
      translation: "我想实现我的目标。",
    },
    {
      word: "mejorar",
      meaning: "改善；提高",
      type: "v.",
      example: "Necesito mejorar mi español.",
      translation: "我需要提高我的西语。",
    },
    {
      word: "decidir",
      meaning: "决定",
      type: "v.",
      example: "Tengo que decidir hoy.",
      translation: "我今天必须做决定。",
    },
    {
      word: "explicar",
      meaning: "解释",
      type: "v.",
      example: "¿Puedes explicarlo otra vez?",
      translation: "你可以再解释一遍吗？",
    },
    {
      word: "recordar",
      meaning: "记得；回忆",
      type: "v.",
      example: "No puedo recordar su nombre.",
      translation: "我想不起他的名字。",
    },
    {
      word: "costumbre",
      meaning: "习惯；风俗",
      type: "n. f.",
      example: "Es una costumbre muy antigua.",
      translation: "这是一个很古老的习俗。",
    },
    {
      word: "consejo",
      meaning: "建议",
      type: "n. m.",
      example: "Gracias por tu consejo.",
      translation: "谢谢你的建议。",
    },
    {
      word: "cambio",
      meaning: "变化；改变",
      type: "n. m.",
      example: "Este cambio es importante.",
      translation: "这个变化很重要。",
    },
    {
      word: "éxito",
      meaning: "成功",
      type: "n. m.",
      example: "El éxito requiere paciencia.",
      translation: "成功需要耐心。",
    },
    {
      word: "fracaso",
      meaning: "失败",
      type: "n. m.",
      example: "El fracaso también enseña.",
      translation: "失败也会教会人东西。",
    },
    {
      word: "desarrollo",
      meaning: "发展",
      type: "n. m.",
      example: "El desarrollo personal es importante.",
      translation: "个人发展很重要。",
    },
    {
      word: "relación",
      meaning: "关系",
      type: "n. f.",
      example: "Tenemos una buena relación.",
      translation: "我们关系很好。",
    },
    {
      word: "experiencia",
      meaning: "经验；经历",
      type: "n. f.",
      example: "Fue una experiencia interesante.",
      translation: "那是一次有趣的经历。",
    },
  ],
};