import { b2Words } from "../data/b2Words";
import { c1Words } from "../data/c1Words";

export type LevelId = "a1" | "a2" | "b1" | "b2" | "c1";

export type WordItem = {
  word: string;
  meaning: string;
  type: string;
  example: string;
  translation: string;
};

function toWordItems(
  words: Array<{
    word: string;
    chinese: string;
    pos: string;
    exampleEs: string;
    exampleZh: string;
  }>,
): WordItem[] {
  return words.map((item) => ({
    word: item.word,
    meaning: item.chinese,
    type: item.pos,
    example: item.exampleEs,
    translation: item.exampleZh,
  }));
}

export const levelNames: Record<LevelId, string> = {
  a1: "DELE A1 基础词汇",
  a2: "DELE A2 初级词汇",
  b1: "DELE B1 中级词汇",
  b2: "DELE B2 高阶词汇",
  c1: "DELE C1 高级词汇",
};

export const wordBank: Record<LevelId, WordItem[]> = {
  a1: [
    {
      word: "hola",
      meaning: "你好",
      type: "interj.",
      example: "Hola, ¿cómo estás?",
      translation: "你好，你怎么样？",
    },
    {
      word: "buenos días",
      meaning: "早上好",
      type: "loc.",
      example: "Buenos días, profesora.",
      translation: "早上好，老师。",
    },
    {
      word: "buenas tardes",
      meaning: "下午好",
      type: "loc.",
      example: "Buenas tardes, señor García.",
      translation: "下午好， García 先生。",
    },
    {
      word: "buenas noches",
      meaning: "晚上好；晚安",
      type: "loc.",
      example: "Buenas noches, hasta mañana.",
      translation: "晚安，明天见。",
    },
    {
      word: "adiós",
      meaning: "再见",
      type: "interj.",
      example: "Adiós, nos vemos pronto.",
      translation: "再见，我们很快再见。",
    },
    {
      word: "hasta luego",
      meaning: "待会儿见；回头见",
      type: "loc.",
      example: "Hasta luego, amigo.",
      translation: "回头见，朋友。",
    },
    {
      word: "gracias",
      meaning: "谢谢",
      type: "interj.",
      example: "Muchas gracias por tu ayuda.",
      translation: "非常感谢你的帮助。",
    },
    {
      word: "por favor",
      meaning: "请",
      type: "loc.",
      example: "Un café, por favor.",
      translation: "请给我一杯咖啡。",
    },
    {
      word: "perdón",
      meaning: "对不起；不好意思",
      type: "interj.",
      example: "Perdón, no entiendo.",
      translation: "不好意思，我不明白。",
    },
    {
      word: "sí",
      meaning: "是；对",
      type: "adv.",
      example: "Sí, quiero aprender español.",
      translation: "是的，我想学习西班牙语。",
    },
    {
      word: "no",
      meaning: "不；没有",
      type: "adv.",
      example: "No tengo tiempo hoy.",
      translation: "我今天没有时间。",
    },
    {
      word: "ser",
      meaning: "是；作为",
      type: "v.",
      example: "Soy estudiante.",
      translation: "我是学生。",
    },
    {
      word: "estar",
      meaning: "在；处于某种状态",
      type: "v.",
      example: "Estoy en casa.",
      translation: "我在家。",
    },
    {
      word: "tener",
      meaning: "有",
      type: "v.",
      example: "Tengo un libro.",
      translation: "我有一本书。",
    },
    {
      word: "llamarse",
      meaning: "叫做；名叫",
      type: "v. pron.",
      example: "Me llamo Ana.",
      translation: "我叫 Ana。",
    },
    {
      word: "vivir",
      meaning: "居住；生活",
      type: "v.",
      example: "Vivo en China.",
      translation: "我住在中国。",
    },
    {
      word: "hablar",
      meaning: "说话；交谈",
      type: "v.",
      example: "Quiero hablar contigo.",
      translation: "我想和你说话。",
    },
    {
      word: "comer",
      meaning: "吃",
      type: "v.",
      example: "Vamos a comer juntos.",
      translation: "我们一起吃饭吧。",
    },
    {
      word: "beber",
      meaning: "喝",
      type: "v.",
      example: "Quiero beber agua.",
      translation: "我想喝水。",
    },
    {
      word: "ir",
      meaning: "去",
      type: "v.",
      example: "Voy a la escuela.",
      translation: "我去学校。",
    },
    {
      word: "venir",
      meaning: "来",
      type: "v.",
      example: "Vengo de casa.",
      translation: "我从家里来。",
    },
    {
      word: "hacer",
      meaning: "做",
      type: "v.",
      example: "Hago los deberes.",
      translation: "我做作业。",
    },
    {
      word: "poder",
      meaning: "能够；可以",
      type: "v.",
      example: "Puedo hablar un poco de español.",
      translation: "我会说一点西班牙语。",
    },
    {
      word: "querer",
      meaning: "想要；喜欢",
      type: "v.",
      example: "Quiero una botella de agua.",
      translation: "我想要一瓶水。",
    },
    {
      word: "saber",
      meaning: "知道；会",
      type: "v.",
      example: "No sé la respuesta.",
      translation: "我不知道答案。",
    },
    {
      word: "necesitar",
      meaning: "需要",
      type: "v.",
      example: "Necesito estudiar más.",
      translation: "我需要多学习。",
    },
    {
      word: "gustar",
      meaning: "喜欢",
      type: "v.",
      example: "Me gusta el café.",
      translation: "我喜欢咖啡。",
    },
    {
      word: "ver",
      meaning: "看见；看",
      type: "v.",
      example: "Veo una película.",
      translation: "我看一部电影。",
    },
    {
      word: "leer",
      meaning: "读",
      type: "v.",
      example: "Leo un libro en español.",
      translation: "我读一本西班牙语书。",
    },
    {
      word: "escribir",
      meaning: "写",
      type: "v.",
      example: "Escribo mi nombre.",
      translation: "我写我的名字。",
    },
    {
      word: "estudiar",
      meaning: "学习",
      type: "v.",
      example: "Estudio español todos los días.",
      translation: "我每天学习西班牙语。",
    },
    {
      word: "trabajar",
      meaning: "工作",
      type: "v.",
      example: "Trabajo por la mañana.",
      translation: "我早上工作。",
    },
    {
      word: "casa",
      meaning: "房子；家",
      type: "n. f.",
      example: "Mi casa está cerca de la escuela.",
      translation: "我家在学校附近。",
    },
    {
      word: "escuela",
      meaning: "学校",
      type: "n. f.",
      example: "La escuela está abierta.",
      translation: "学校开着。",
    },
    {
      word: "clase",
      meaning: "课；班级",
      type: "n. f.",
      example: "Tengo clase a las nueve.",
      translation: "我九点有课。",
    },
    {
      word: "libro",
      meaning: "书",
      type: "n. m.",
      example: "Este libro es interesante.",
      translation: "这本书很有趣。",
    },
    {
      word: "cuaderno",
      meaning: "笔记本",
      type: "n. m.",
      example: "Escribo en mi cuaderno.",
      translation: "我写在我的笔记本里。",
    },
    {
      word: "bolígrafo",
      meaning: "圆珠笔",
      type: "n. m.",
      example: "Necesito un bolígrafo azul.",
      translation: "我需要一支蓝色圆珠笔。",
    },
    {
      word: "mesa",
      meaning: "桌子",
      type: "n. f.",
      example: "El libro está sobre la mesa.",
      translation: "书在桌子上。",
    },
    {
      word: "silla",
      meaning: "椅子",
      type: "n. f.",
      example: "La silla es cómoda.",
      translation: "这把椅子很舒服。",
    },
    {
      word: "puerta",
      meaning: "门",
      type: "n. f.",
      example: "La puerta está cerrada.",
      translation: "门关着。",
    },
    {
      word: "ventana",
      meaning: "窗户",
      type: "n. f.",
      example: "Abro la ventana.",
      translation: "我打开窗户。",
    },
    {
      word: "familia",
      meaning: "家庭；家人",
      type: "n. f.",
      example: "Mi familia es muy grande.",
      translation: "我的家人很多。",
    },
    {
      word: "madre",
      meaning: "母亲",
      type: "n. f.",
      example: "Mi madre trabaja en un hospital.",
      translation: "我母亲在医院工作。",
    },
    {
      word: "padre",
      meaning: "父亲",
      type: "n. m.",
      example: "Mi padre cocina muy bien.",
      translation: "我父亲做饭很好。",
    },
    {
      word: "hermano",
      meaning: "兄弟",
      type: "n. m.",
      example: "Tengo un hermano menor.",
      translation: "我有一个弟弟。",
    },
    {
      word: "hermana",
      meaning: "姐妹",
      type: "n. f.",
      example: "Mi hermana estudia español.",
      translation: "我姐姐学习西班牙语。",
    },
    {
      word: "amigo",
      meaning: "朋友",
      type: "n. m.",
      example: "Mi amigo vive en Madrid.",
      translation: "我的朋友住在马德里。",
    },
    {
      word: "persona",
      meaning: "人",
      type: "n. f.",
      example: "Es una persona amable.",
      translation: "他是一个友善的人。",
    },
    {
      word: "hombre",
      meaning: "男人",
      type: "n. m.",
      example: "El hombre habla español.",
      translation: "这个男人说西班牙语。",
    },
    {
      word: "mujer",
      meaning: "女人",
      type: "n. f.",
      example: "La mujer trabaja aquí.",
      translation: "这个女人在这里工作。",
    },
    {
      word: "niño",
      meaning: "男孩；孩子",
      type: "n. m.",
      example: "El niño lee un cuento.",
      translation: "这个男孩读一个故事。",
    },
    {
      word: "ciudad",
      meaning: "城市",
      type: "n. f.",
      example: "Madrid es una ciudad grande.",
      translation: "马德里是一座大城市。",
    },
    {
      word: "calle",
      meaning: "街道",
      type: "n. f.",
      example: "La calle es tranquila.",
      translation: "这条街很安静。",
    },
    {
      word: "tienda",
      meaning: "商店",
      type: "n. f.",
      example: "Voy a la tienda.",
      translation: "我去商店。",
    },
    {
      word: "restaurante",
      meaning: "餐厅",
      type: "n. m.",
      example: "Comemos en un restaurante.",
      translation: "我们在一家餐厅吃饭。",
    },
    {
      word: "hotel",
      meaning: "酒店",
      type: "n. m.",
      example: "El hotel está en el centro.",
      translation: "酒店在市中心。",
    },
    {
      word: "estación",
      meaning: "车站",
      type: "n. f.",
      example: "La estación está cerca.",
      translation: "车站很近。",
    },
    {
      word: "coche",
      meaning: "汽车",
      type: "n. m.",
      example: "Tengo un coche rojo.",
      translation: "我有一辆红色的汽车。",
    },
    {
      word: "autobús",
      meaning: "公交车",
      type: "n. m.",
      example: "Voy al trabajo en autobús.",
      translation: "我坐公交车去上班。",
    },
    {
      word: "tren",
      meaning: "火车",
      type: "n. m.",
      example: "El tren sale a las ocho.",
      translation: "火车八点出发。",
    },
    {
      word: "metro",
      meaning: "地铁",
      type: "n. m.",
      example: "Tomo el metro todos los días.",
      translation: "我每天坐地铁。",
    },
    {
      word: "comida",
      meaning: "食物；饭",
      type: "n. f.",
      example: "La comida está muy rica.",
      translation: "食物很好吃。",
    },
    {
      word: "pan",
      meaning: "面包",
      type: "n. m.",
      example: "Compro pan en la tienda.",
      translation: "我在商店买面包。",
    },
    {
      word: "agua",
      meaning: "水",
      type: "n. f.",
      example: "Quiero un vaso de agua.",
      translation: "我想要一杯水。",
    },
    {
      word: "café",
      meaning: "咖啡",
      type: "n. m.",
      example: "Tomo café por la mañana.",
      translation: "我早上喝咖啡。",
    },
    {
      word: "leche",
      meaning: "牛奶",
      type: "n. f.",
      example: "Bebo leche con café.",
      translation: "我喝加牛奶的咖啡。",
    },
    {
      word: "fruta",
      meaning: "水果",
      type: "n. f.",
      example: "Como fruta todos los días.",
      translation: "我每天吃水果。",
    },
    {
      word: "manzana",
      meaning: "苹果",
      type: "n. f.",
      example: "Quiero una manzana.",
      translation: "我想要一个苹果。",
    },
    {
      word: "arroz",
      meaning: "米饭",
      type: "n. m.",
      example: "Me gusta el arroz.",
      translation: "我喜欢米饭。",
    },
    {
      word: "carne",
      meaning: "肉",
      type: "n. f.",
      example: "No como mucha carne.",
      translation: "我不吃很多肉。",
    },
    {
      word: "pescado",
      meaning: "鱼；鱼肉",
      type: "n. m.",
      example: "El pescado está bueno.",
      translation: "鱼很好吃。",
    },
    {
      word: "día",
      meaning: "天；日子",
      type: "n. m.",
      example: "Hoy es un buen día.",
      translation: "今天是个好日子。",
    },
    {
      word: "semana",
      meaning: "星期；周",
      type: "n. f.",
      example: "Esta semana tengo mucho trabajo.",
      translation: "这周我有很多工作。",
    },
    {
      word: "mes",
      meaning: "月",
      type: "n. m.",
      example: "Este mes estudio mucho.",
      translation: "这个月我学习很多。",
    },
    {
      word: "año",
      meaning: "年",
      type: "n. m.",
      example: "Este año quiero viajar.",
      translation: "今年我想旅行。",
    },
    {
      word: "hoy",
      meaning: "今天",
      type: "adv.",
      example: "Hoy estudio español.",
      translation: "今天我学习西班牙语。",
    },
    {
      word: "mañana",
      meaning: "明天；早晨",
      type: "n. f. / adv.",
      example: "Mañana tengo clase.",
      translation: "明天我有课。",
    },
    {
      word: "ayer",
      meaning: "昨天",
      type: "adv.",
      example: "Ayer fui al cine.",
      translation: "昨天我去了电影院。",
    },
    {
      word: "ahora",
      meaning: "现在",
      type: "adv.",
      example: "Ahora estoy en casa.",
      translation: "现在我在家。",
    },
    {
      word: "zapato",
      meaning: "鞋",
      type: "n. m.",
      example: "Este zapato es cómodo.",
      translation: "这只鞋很舒服。",
    },
    {
      word: "abrigo",
      meaning: "外套；大衣",
      type: "n. m.",
      example: "Uso abrigo en invierno.",
      translation: "我冬天穿大衣。",
    },
    {
      word: "supermercado",
      meaning: "超市",
      type: "n. m.",
      example: "Voy al supermercado los sábados.",
      translation: "我周六去超市。",
    },
    {
      word: "cuerpo",
      meaning: "身体",
      type: "n. m.",
      example: "El cuerpo necesita descanso.",
      translation: "身体需要休息。",
    },
    {
      word: "mano",
      meaning: "手",
      type: "n. f.",
      example: "Levanto la mano.",
      translation: "我举手。",
    },
    {
      word: "ojo",
      meaning: "眼睛",
      type: "n. m.",
      example: "Tengo los ojos marrones.",
      translation: "我有棕色的眼睛。",
    },
    {
      word: "boca",
      meaning: "嘴",
      type: "n. f.",
      example: "Abre la boca, por favor.",
      translation: "请张开嘴。",
    },
    {
      word: "pie",
      meaning: "脚",
      type: "n. m.",
      example: "Me duele el pie.",
      translation: "我脚疼。",
    },
    {
      word: "enfermo",
      meaning: "生病的",
      type: "adj.",
      example: "Estoy enfermo hoy.",
      translation: "我今天生病了。",
    },
    {
      word: "temprano",
      meaning: "早地；早的",
      type: "adv. / adj.",
      example: "Me levanto temprano.",
      translation: "我起得早。",
    },
    {
      word: "tarde",
      meaning: "晚地；迟的",
      type: "adv. / adj.",
      example: "Llego tarde a clase.",
      translation: "我上课迟到了。",
    },
    {
      word: "siempre",
      meaning: "总是",
      type: "adv.",
      example: "Siempre estudio por la noche.",
      translation: "我总是在晚上学习。",
    },
    {
      word: "nunca",
      meaning: "从不",
      type: "adv.",
      example: "Nunca bebo café por la noche.",
      translation: "我晚上从不喝咖啡。",
    },
    {
      word: "a veces",
      meaning: "有时",
      type: "loc. adv.",
      example: "A veces camino al trabajo.",
      translation: "我有时走路去上班。",
    },
    {
      word: "desayunar",
      meaning: "吃早餐",
      type: "v.",
      example: "Desayuno a las ocho.",
      translation: "我八点吃早餐。",
    },
    {
      word: "cenar",
      meaning: "吃晚饭",
      type: "v.",
      example: "Cenamos en casa.",
      translation: "我们在家吃晚饭。",
    },
    {
      word: "levantarse",
      meaning: "起床",
      type: "v. pron.",
      example: "Me levanto a las siete.",
      translation: "我七点起床。",
    },
    {
      word: "dormir",
      meaning: "睡觉",
      type: "v.",
      example: "Quiero dormir ocho horas.",
      translation: "我想睡八个小时。",
    },
    {
      word: "caminar",
      meaning: "走路；散步",
      type: "v.",
      example: "Camino al parque.",
      translation: "我走路去公园。",
    },
    {
      word: "correr",
      meaning: "跑",
      type: "v.",
      example: "Me gusta correr por la mañana.",
      translation: "我喜欢早上跑步。",
    },
    {
      word: "nariz",
      meaning: "鼻子",
      type: "n. f.",
      example: "Me duele la nariz.",
      translation: "我鼻子疼。",
    },
    {
      word: "oreja",
      meaning: "耳朵",
      type: "n. f.",
      example: "La niña tiene las orejas pequeñas.",
      translation: "女孩的耳朵很小。",
    },
    {
      word: "pelo",
      meaning: "头发",
      type: "n. m.",
      example: "Tengo el pelo negro.",
      translation: "我有黑色的头发。",
    },
    {
      word: "brazo",
      meaning: "手臂",
      type: "n. m.",
      example: "Levanto el brazo.",
      translation: "我抬起手臂。",
    },
    {
      word: "pierna",
      meaning: "腿",
      type: "n. f.",
      example: "Me duele la pierna.",
      translation: "我腿疼。",
    },
    {
      word: "espalda",
      meaning: "背部",
      type: "n. f.",
      example: "Tengo dolor de espalda.",
      translation: "我背疼。",
    },
    {
      word: "corazón",
      meaning: "心；心脏",
      type: "n. m.",
      example: "El corazón late rápido.",
      translation: "心跳得很快。",
    },
    {
      word: "pollo",
      meaning: "鸡肉；鸡",
      type: "n. m.",
      example: "Quiero pollo para cenar.",
      translation: "我晚饭想吃鸡肉。",
    },
    {
      word: "queso",
      meaning: "奶酪",
      type: "n. m.",
      example: "El queso está en la mesa.",
      translation: "奶酪在桌子上。",
    },
    {
      word: "huevo",
      meaning: "鸡蛋",
      type: "n. m.",
      example: "Como un huevo en el desayuno.",
      translation: "我早餐吃一个鸡蛋。",
    },
    {
      word: "naranja",
      meaning: "橙子；橙色",
      type: "n. f. / adj.",
      example: "Quiero una naranja.",
      translation: "我想要一个橙子。",
    },
    {
      word: "plátano",
      meaning: "香蕉",
      type: "n. m.",
      example: "El plátano está maduro.",
      translation: "香蕉熟了。",
    },
    {
      word: "tomate",
      meaning: "番茄",
      type: "n. m.",
      example: "Pongo tomate en la ensalada.",
      translation: "我把番茄放进沙拉里。",
    },
    {
      word: "patata",
      meaning: "土豆",
      type: "n. f.",
      example: "Comemos patatas con pescado.",
      translation: "我们吃土豆配鱼。",
    },
    {
      word: "ensalada",
      meaning: "沙拉",
      type: "n. f.",
      example: "La ensalada es fresca.",
      translation: "沙拉很新鲜。",
    },
    {
      word: "sopa",
      meaning: "汤",
      type: "n. f.",
      example: "La sopa está caliente.",
      translation: "汤是热的。",
    },
    {
      word: "azúcar",
      meaning: "糖",
      type: "n. m.",
      example: "No quiero azúcar en el café.",
      translation: "我咖啡里不要糖。",
    },
    {
      word: "sal",
      meaning: "盐",
      type: "n. f.",
      example: "La sopa necesita sal.",
      translation: "汤需要盐。",
    },
    {
      word: "aceite",
      meaning: "油",
      type: "n. m.",
      example: "Uso aceite para cocinar.",
      translation: "我用油做饭。",
    },
    {
      word: "sofá",
      meaning: "沙发",
      type: "n. m.",
      example: "El sofá está en el salón.",
      translation: "沙发在客厅里。",
    },
  ],

  a2: [
    {
      word: "viajar",
      meaning: "旅行",
      type: "v.",
      example: "Me gusta viajar en verano.",
      translation: "我喜欢在夏天旅行。",
    },
    {
      word: "billete",
      meaning: "票；车票",
      type: "n. m.",
      example: "Necesito comprar un billete de tren.",
      translation: "我需要买一张火车票。",
    },
    {
      word: "pasaporte",
      meaning: "护照",
      type: "n. m.",
      example: "No olvides tu pasaporte.",
      translation: "不要忘记你的护照。",
    },
    {
      word: "maleta",
      meaning: "行李箱",
      type: "n. f.",
      example: "Mi maleta es muy pesada.",
      translation: "我的行李箱很重。",
    },
    {
      word: "aeropuerto",
      meaning: "机场",
      type: "n. m.",
      example: "El aeropuerto está lejos del centro.",
      translation: "机场离市中心很远。",
    },
    {
      word: "vuelo",
      meaning: "航班；飞行",
      type: "n. m.",
      example: "Mi vuelo sale a las diez.",
      translation: "我的航班十点出发。",
    },
    {
      word: "retraso",
      meaning: "延误；迟到",
      type: "n. m.",
      example: "El tren tiene retraso.",
      translation: "火车晚点了。",
    },
    {
      word: "habitación",
      meaning: "房间",
      type: "n. f.",
      example: "La habitación es muy cómoda.",
      translation: "这个房间很舒服。",
    },
    {
      word: "reserva",
      meaning: "预订",
      type: "n. f.",
      example: "Tengo una reserva para dos personas.",
      translation: "我有一个两人预订。",
    },
    {
      word: "mapa",
      meaning: "地图",
      type: "n. m.",
      example: "Necesito un mapa de la ciudad.",
      translation: "我需要一张城市地图。",
    },
    {
      word: "dirección",
      meaning: "地址；方向",
      type: "n. f.",
      example: "¿Cuál es tu dirección?",
      translation: "你的地址是什么？",
    },
    {
      word: "derecha",
      meaning: "右边",
      type: "n. f.",
      example: "Gira a la derecha.",
      translation: "向右转。",
    },
    {
      word: "izquierda",
      meaning: "左边",
      type: "n. f.",
      example: "La farmacia está a la izquierda.",
      translation: "药店在左边。",
    },
    {
      word: "cerca",
      meaning: "近",
      type: "adv.",
      example: "El supermercado está cerca.",
      translation: "超市很近。",
    },
    {
      word: "lejos",
      meaning: "远",
      type: "adv.",
      example: "Mi casa está lejos de aquí.",
      translation: "我家离这里很远。",
    },
    {
      word: "comprar",
      meaning: "买",
      type: "v.",
      example: "Quiero comprar una chaqueta.",
      translation: "我想买一件夹克。",
    },
    {
      word: "vender",
      meaning: "卖",
      type: "v.",
      example: "Esta tienda vende frutas.",
      translation: "这家商店卖水果。",
    },
    {
      word: "probar",
      meaning: "试；尝试；试穿",
      type: "v.",
      example: "¿Puedo probar esta camisa?",
      translation: "我可以试穿这件衬衫吗？",
    },
    {
      word: "pagar",
      meaning: "付款",
      type: "v.",
      example: "Quiero pagar con tarjeta.",
      translation: "我想用卡付款。",
    },
    {
      word: "costar",
      meaning: "花费；价值",
      type: "v.",
      example: "¿Cuánto cuesta este libro?",
      translation: "这本书多少钱？",
    },
    {
      word: "precio",
      meaning: "价格",
      type: "n. m.",
      example: "El precio es muy alto.",
      translation: "价格很高。",
    },
    {
      word: "barato",
      meaning: "便宜的",
      type: "adj.",
      example: "Este restaurante es barato.",
      translation: "这家餐厅很便宜。",
    },
    {
      word: "caro",
      meaning: "贵的",
      type: "adj.",
      example: "El hotel es demasiado caro.",
      translation: "这家酒店太贵了。",
    },
    {
      word: "descuento",
      meaning: "折扣",
      type: "n. m.",
      example: "Hay un descuento del veinte por ciento.",
      translation: "有八折优惠。",
    },
    {
      word: "dinero",
      meaning: "钱",
      type: "n. m.",
      example: "No tengo mucho dinero.",
      translation: "我没有很多钱。",
    },
    {
      word: "tarjeta",
      meaning: "卡；银行卡",
      type: "n. f.",
      example: "Pago con tarjeta.",
      translation: "我用卡付款。",
    },
    {
      word: "efectivo",
      meaning: "现金",
      type: "n. m.",
      example: "Prefiero pagar en efectivo.",
      translation: "我更喜欢用现金付款。",
    },
    {
      word: "recibo",
      meaning: "收据；小票",
      type: "n. m.",
      example: "¿Me da el recibo, por favor?",
      translation: "请给我收据好吗？",
    },
    {
      word: "ropa",
      meaning: "衣服",
      type: "n. f.",
      example: "Necesito comprar ropa nueva.",
      translation: "我需要买新衣服。",
    },
    {
      word: "camisa",
      meaning: "衬衫",
      type: "n. f.",
      example: "Esta camisa es blanca.",
      translation: "这件衬衫是白色的。",
    },
    {
      word: "pantalón",
      meaning: "裤子",
      type: "n. m.",
      example: "El pantalón me queda bien.",
      translation: "这条裤子很合身。",
    },
    {
      word: "zapatos",
      meaning: "鞋子",
      type: "n. m. pl.",
      example: "Mis zapatos son negros.",
      translation: "我的鞋是黑色的。",
    },
    {
      word: "talla",
      meaning: "尺码",
      type: "n. f.",
      example: "¿Tiene una talla más grande?",
      translation: "有大一号的吗？",
    },
    {
      word: "color",
      meaning: "颜色",
      type: "n. m.",
      example: "Me gusta este color.",
      translation: "我喜欢这个颜色。",
    },
    {
      word: "cambiar",
      meaning: "更换；改变",
      type: "v.",
      example: "Quiero cambiar esta camiseta.",
      translation: "我想换这件 T 恤。",
    },
    {
      word: "trabajo",
      meaning: "工作",
      type: "n. m.",
      example: "Tengo mucho trabajo esta semana.",
      translation: "这周我有很多工作。",
    },
    {
      word: "oficina",
      meaning: "办公室",
      type: "n. f.",
      example: "Trabajo en una oficina.",
      translation: "我在办公室工作。",
    },
    {
      word: "empresa",
      meaning: "公司",
      type: "n. f.",
      example: "Mi empresa está en el centro.",
      translation: "我的公司在市中心。",
    },
    {
      word: "jefe",
      meaning: "老板；上司",
      type: "n. m.",
      example: "Mi jefe es muy amable.",
      translation: "我的老板很友善。",
    },
    {
      word: "compañero",
      meaning: "同事；同伴",
      type: "n. m.",
      example: "Mi compañero habla inglés.",
      translation: "我的同事会说英语。",
    },
    {
      word: "reunión",
      meaning: "会议",
      type: "n. f.",
      example: "Tengo una reunión a las tres.",
      translation: "我三点有一个会议。",
    },
    {
      word: "horario",
      meaning: "时间表；日程",
      type: "n. m.",
      example: "Mi horario cambia cada semana.",
      translation: "我的时间表每周都变。",
    },
    {
      word: "descansar",
      meaning: "休息",
      type: "v.",
      example: "Necesito descansar un poco.",
      translation: "我需要休息一下。",
    },
    {
      word: "terminar",
      meaning: "结束；完成",
      type: "v.",
      example: "Termino el trabajo a las seis.",
      translation: "我六点结束工作。",
    },
    {
      word: "empezar",
      meaning: "开始",
      type: "v.",
      example: "La clase empieza a las nueve.",
      translation: "课九点开始。",
    },
    {
      word: "aprender",
      meaning: "学习",
      type: "v.",
      example: "Aprendo español todos los días.",
      translation: "我每天学习西班牙语。",
    },
    {
      word: "entender",
      meaning: "理解；明白",
      type: "v.",
      example: "No entiendo esta palabra.",
      translation: "我不明白这个单词。",
    },
    {
      word: "recordar",
      meaning: "记得",
      type: "v.",
      example: "No recuerdo su número.",
      translation: "我不记得他的号码。",
    },
    {
      word: "olvidar",
      meaning: "忘记",
      type: "v.",
      example: "Olvido muchas palabras nuevas.",
      translation: "我忘记很多新单词。",
    },
    {
      word: "preguntar",
      meaning: "问",
      type: "v.",
      example: "Quiero preguntar algo.",
      translation: "我想问点事情。",
    },
    {
      word: "responder",
      meaning: "回答",
      type: "v.",
      example: "Puedes responder en español.",
      translation: "你可以用西班牙语回答。",
    },
    {
      word: "explicar",
      meaning: "解释",
      type: "v.",
      example: "El profesor explica la gramática.",
      translation: "老师解释语法。",
    },
    {
      word: "practicar",
      meaning: "练习",
      type: "v.",
      example: "Practico la pronunciación.",
      translation: "我练习发音。",
    },
    {
      word: "salud",
      meaning: "健康",
      type: "n. f.",
      example: "La salud es muy importante.",
      translation: "健康很重要。",
    },
    {
      word: "médico",
      meaning: "医生",
      type: "n. m.",
      example: "Necesito ver a un médico.",
      translation: "我需要看医生。",
    },
    {
      word: "hospital",
      meaning: "医院",
      type: "n. m.",
      example: "El hospital está cerca.",
      translation: "医院很近。",
    },
    {
      word: "farmacia",
      meaning: "药店",
      type: "n. f.",
      example: "Voy a la farmacia.",
      translation: "我去药店。",
    },
    {
      word: "medicina",
      meaning: "药；医学",
      type: "n. f.",
      example: "Tomo la medicina por la noche.",
      translation: "我晚上吃药。",
    },
    {
      word: "dolor",
      meaning: "疼痛",
      type: "n. m.",
      example: "Tengo dolor de cabeza.",
      translation: "我头疼。",
    },
    {
      word: "cabeza",
      meaning: "头",
      type: "n. f.",
      example: "Me duele la cabeza.",
      translation: "我头疼。",
    },
    {
      word: "estómago",
      meaning: "胃；肚子",
      type: "n. m.",
      example: "Me duele el estómago.",
      translation: "我胃疼。",
    },
    {
      word: "fiebre",
      meaning: "发烧",
      type: "n. f.",
      example: "Tengo fiebre desde ayer.",
      translation: "我从昨天开始发烧。",
    },
    {
      word: "cansado",
      meaning: "累的",
      type: "adj.",
      example: "Estoy cansado después del trabajo.",
      translation: "下班后我很累。",
    },
    {
      word: "contento",
      meaning: "高兴的",
      type: "adj.",
      example: "Estoy contento con mi progreso.",
      translation: "我对自己的进步很高兴。",
    },
    {
      word: "triste",
      meaning: "难过的",
      type: "adj.",
      example: "Estoy triste hoy.",
      translation: "我今天很难过。",
    },
    {
      word: "ocupado",
      meaning: "忙的",
      type: "adj.",
      example: "Estoy ocupado esta tarde.",
      translation: "我今天下午很忙。",
    },
    {
      word: "libre",
      meaning: "空闲的；自由的",
      type: "adj.",
      example: "Estoy libre el sábado.",
      translation: "我周六有空。",
    },
    {
      word: "rápido",
      meaning: "快的",
      type: "adj.",
      example: "El tren es muy rápido.",
      translation: "火车很快。",
    },
    {
      word: "lento",
      meaning: "慢的",
      type: "adj.",
      example: "El autobús es lento.",
      translation: "公交车很慢。",
    },
    {
      word: "fácil",
      meaning: "容易的",
      type: "adj.",
      example: "Este ejercicio es fácil.",
      translation: "这个练习很容易。",
    },
    {
      word: "difícil",
      meaning: "困难的",
      type: "adj.",
      example: "La gramática es difícil.",
      translation: "语法很难。",
    },
    {
      word: "importante",
      meaning: "重要的",
      type: "adj.",
      example: "Es una pregunta importante.",
      translation: "这是一个重要的问题。",
    },
    {
      word: "tiempo",
      meaning: "时间；天气",
      type: "n. m.",
      example: "No tengo tiempo ahora.",
      translation: "我现在没有时间。",
    },
    {
      word: "calor",
      meaning: "热",
      type: "n. m.",
      example: "Hace mucho calor hoy.",
      translation: "今天很热。",
    },
    {
      word: "frío",
      meaning: "冷；寒冷",
      type: "n. m. / adj.",
      example: "Hace frío por la mañana.",
      translation: "早上很冷。",
    },
    {
      word: "lluvia",
      meaning: "雨",
      type: "n. f.",
      example: "Hay mucha lluvia en abril.",
      translation: "四月雨很多。",
    },
    {
      word: "sol",
      meaning: "太阳；阳光",
      type: "n. m.",
      example: "Hoy hace sol.",
      translation: "今天有太阳。",
    },
    {
      word: "nube",
      meaning: "云",
      type: "n. f.",
      example: "Hay muchas nubes en el cielo.",
      translation: "天空中有很多云。",
    },
    {
      word: "reservar",
      meaning: "预订",
      type: "v.",
      example: "Quiero reservar una habitación para dos noches.",
      translation: "我想预订一个房间住两晚。",
    },
    {
      word: "cancelar",
      meaning: "取消",
      type: "v.",
      example: "Necesito cancelar la reserva.",
      translation: "我需要取消预订。",
    },
    {
      word: "confirmar",
      meaning: "确认",
      type: "v.",
      example: "Puedes confirmar la dirección por correo.",
      translation: "你可以通过邮件确认地址。",
    },
    {
      word: "alojamiento",
      meaning: "住宿",
      type: "n. m.",
      example: "Buscamos alojamiento cerca del centro.",
      translation: "我们在市中心附近找住宿。",
    },
    {
      word: "recepción",
      meaning: "前台；接待处",
      type: "n. f.",
      example: "La recepción está abierta todo el día.",
      translation: "前台全天开放。",
    },
    {
      word: "equipaje",
      meaning: "行李",
      type: "n. m.",
      example: "Mi equipaje está en la habitación.",
      translation: "我的行李在房间里。",
    },
    {
      word: "salida",
      meaning: "出发；出口",
      type: "n. f.",
      example: "La salida es a las ocho.",
      translation: "出发时间是八点。",
    },
    {
      word: "llegada",
      meaning: "到达",
      type: "n. f.",
      example: "La llegada está prevista para las diez.",
      translation: "预计十点到达。",
    },
    {
      word: "destino",
      meaning: "目的地",
      type: "n. m.",
      example: "Nuestro destino es Sevilla.",
      translation: "我们的目的地是塞维利亚。",
    },
    {
      word: "asiento",
      meaning: "座位",
      type: "n. m.",
      example: "Mi asiento está junto a la ventana.",
      translation: "我的座位靠窗。",
    },
    {
      word: "entrada",
      meaning: "门票；入口",
      type: "n. f.",
      example: "Compré una entrada para el museo.",
      translation: "我买了一张博物馆门票。",
    },
    {
      word: "cita",
      meaning: "预约；约会",
      type: "n. f.",
      example: "Tengo una cita con el médico.",
      translation: "我和医生有一个预约。",
    },
    {
      word: "receta",
      meaning: "处方；食谱",
      type: "n. f.",
      example: "El médico me da una receta.",
      translation: "医生给我一张处方。",
    },
    {
      word: "rebaja",
      meaning: "折扣；减价",
      type: "n. f.",
      example: "Esta tienda tiene muchas rebajas.",
      translation: "这家店有很多折扣。",
    },
    {
      word: "probarse",
      meaning: "试穿",
      type: "v. pron.",
      example: "Quiero probarme estos zapatos.",
      translation: "我想试穿这双鞋。",
    },
    {
      word: "devolver",
      meaning: "退还；归还",
      type: "v.",
      example: "Quiero devolver este producto.",
      translation: "我想退掉这个商品。",
    },
    {
      word: "cajero",
      meaning: "收银员；取款机",
      type: "n. m.",
      example: "El cajero está al fondo.",
      translation: "收银台在里面。",
    },
    {
      word: "cliente",
      meaning: "顾客；客户",
      type: "n. m. / f.",
      example: "El cliente espera en la tienda.",
      translation: "顾客在店里等。",
    },
    {
      word: "producto",
      meaning: "产品",
      type: "n. m.",
      example: "Este producto es nuevo.",
      translation: "这个产品是新的。",
    },
    {
      word: "calidad",
      meaning: "质量",
      type: "n. f.",
      example: "La calidad es buena.",
      translation: "质量很好。",
    },
    {
      word: "mudarse",
      meaning: "搬家",
      type: "v. pron.",
      example: "Nos vamos a mudar a otra ciudad.",
      translation: "我们要搬到另一个城市。",
    },
    {
      word: "alquilar",
      meaning: "租赁",
      type: "v.",
      example: "Quiero alquilar un piso pequeño.",
      translation: "我想租一套小公寓。",
    },
    {
      word: "piso",
      meaning: "公寓；楼层",
      type: "n. m.",
      example: "Vivo en un piso cerca del metro.",
      translation: "我住在地铁附近的一套公寓里。",
    },
    {
      word: "vecino",
      meaning: "男邻居",
      type: "n. m.",
      example: "Mi vecino es muy amable.",
      translation: "我的邻居很友善。",
    },
    {
      word: "vecina",
      meaning: "女邻居",
      type: "n. f.",
      example: "La vecina tiene un perro.",
      translation: "女邻居有一只狗。",
    },
    {
      word: "ascensor",
      meaning: "电梯",
      type: "n. m.",
      example: "El ascensor no funciona.",
      translation: "电梯坏了。",
    },
    {
      word: "garaje",
      meaning: "车库",
      type: "n. m.",
      example: "El coche está en el garaje.",
      translation: "车在车库里。",
    },
    {
      word: "calefacción",
      meaning: "暖气",
      type: "n. f.",
      example: "La calefacción está encendida.",
      translation: "暖气开着。",
    },
    {
      word: "aire acondicionado",
      meaning: "空调",
      type: "n. m.",
      example: "Necesito aire acondicionado en verano.",
      translation: "夏天我需要空调。",
    },
    {
      word: "factura",
      meaning: "账单；发票",
      type: "n. f.",
      example: "Tengo que pagar la factura de la luz.",
      translation: "我得付电费账单。",
    },
    {
      word: "gasto",
      meaning: "花费；开支",
      type: "n. m.",
      example: "Los gastos de este mes son altos.",
      translation: "这个月的开支很高。",
    },
    {
      word: "ahorrar",
      meaning: "储蓄；节省",
      type: "v.",
      example: "Quiero ahorrar dinero para viajar.",
      translation: "我想存钱去旅行。",
    },
    {
      word: "gastar",
      meaning: "花费",
      type: "v.",
      example: "No quiero gastar mucho dinero.",
      translation: "我不想花太多钱。",
    },
    {
      word: "moneda",
      meaning: "硬币；货币",
      type: "n. f.",
      example: "Tengo una moneda en el bolsillo.",
      translation: "我口袋里有一枚硬币。",
    },
    {
      word: "cajero automático",
      meaning: "自动取款机",
      type: "n. m.",
      example: "Hay un cajero automático en la esquina.",
      translation: "拐角处有一台自动取款机。",
    },
    {
      word: "contraseña",
      meaning: "密码",
      type: "n. f.",
      example: "No recuerdo mi contraseña.",
      translation: "我不记得我的密码了。",
    },
    {
      word: "pantalla",
      meaning: "屏幕",
      type: "n. f.",
      example: "La pantalla del móvil es grande.",
      translation: "手机屏幕很大。",
    },
    {
      word: "teclado",
      meaning: "键盘",
      type: "n. m.",
      example: "Uso el teclado para escribir.",
      translation: "我用键盘打字。",
    },
    {
      word: "ratón",
      meaning: "鼠标；老鼠",
      type: "n. m.",
      example: "El ratón del ordenador no funciona.",
      translation: "电脑鼠标不能用了。",
    },
    {
      word: "archivo",
      meaning: "文件",
      type: "n. m.",
      example: "Guardo el archivo en el ordenador.",
      translation: "我把文件保存在电脑里。",
    },
    {
      word: "describir",
      meaning: "描述",
      type: "v.",
      example: "Puedes describir tu casa.",
      translation: "你可以描述你的家。",
    },
    {
      word: "comparar",
      meaning: "比较",
      type: "v.",
      example: "Quiero comparar estos dos hoteles.",
      translation: "我想比较这两家酒店。",
    },
    {
      word: "empeorar",
      meaning: "变差；恶化",
      type: "v.",
      example: "El tiempo puede empeorar mañana.",
      translation: "天气明天可能会变差。",
    },
    {
      word: "entregar",
      meaning: "交付；提交",
      type: "v.",
      example: "Tengo que entregar el formulario hoy.",
      translation: "我今天必须提交表格。",
    },
    {
      word: "recoger",
      meaning: "领取；收拾",
      type: "v.",
      example: "Voy a recoger el paquete por la tarde.",
      translation: "我下午去取包裹。",
    },
    {
      word: "paquete",
      meaning: "包裹",
      type: "n. m.",
      example: "El paquete llega mañana.",
      translation: "包裹明天到。",
    },
    {
      word: "envío",
      meaning: "寄送；配送",
      type: "n. m.",
      example: "El envío es gratuito.",
      translation: "配送是免费的。",
    },
    {
      word: "dirección de envío",
      meaning: "收货地址",
      type: "loc. n.",
      example: "Escribo la dirección de envío.",
      translation: "我填写收货地址。",
    },
    {
      word: "deporte",
      meaning: "运动",
      type: "n. m.",
      example: "El deporte es bueno para la salud.",
      translation: "运动对健康有好处。",
    },
    {
      word: "natación",
      meaning: "游泳",
      type: "n. f.",
      example: "Practico natación los domingos.",
      translation: "我周日练习游泳。",
    },
    {
      word: "senderismo",
      meaning: "徒步",
      type: "n. m.",
      example: "Me gusta hacer senderismo en otoño.",
      translation: "我喜欢秋天徒步。",
    },
    {
      word: "gimnasio",
      meaning: "健身房",
      type: "n. m.",
      example: "Voy al gimnasio después del trabajo.",
      translation: "我下班后去健身房。",
    },
    {
      word: "entrada principal",
      meaning: "主入口",
      type: "loc. n.",
      example: "La entrada principal está cerrada.",
      translation: "主入口关着。",
    },
    {
      word: "planta baja",
      meaning: "一楼；底层",
      type: "loc. n.",
      example: "La recepción está en la planta baja.",
      translation: "前台在一楼。",
    },
    {
      word: "primer piso",
      meaning: "二楼；第一层",
      type: "loc. n.",
      example: "Mi habitación está en el primer piso.",
      translation: "我的房间在二楼。",
    },
    {
      word: "segundo piso",
      meaning: "三楼；第二层",
      type: "loc. n.",
      example: "La oficina está en el segundo piso.",
      translation: "办公室在三楼。",
    },
    {
      word: "ruido",
      meaning: "噪音",
      type: "n. m.",
      example: "Hay mucho ruido en la calle.",
      translation: "街上很吵。",
    },
    {
      word: "silencio",
      meaning: "安静；沉默",
      type: "n. m.",
      example: "Necesito silencio para estudiar.",
      translation: "我需要安静来学习。",
    },
    {
      word: "seguridad",
      meaning: "安全",
      type: "n. f.",
      example: "La seguridad del edificio es buena.",
      translation: "这栋楼的安全性很好。",
    },
    {
      word: "peligro",
      meaning: "危险",
      type: "n. m.",
      example: "No hay peligro aquí.",
      translation: "这里没有危险。",
    },
    {
      word: "matrícula",
      meaning: "注册；报名",
      type: "n. f.",
      example: "Tengo que hacer la matrícula esta semana.",
      translation: "我这周要完成注册。",
    },
    {
      word: "curso",
      meaning: "课程",
      type: "n. m.",
      example: "Este curso empieza en septiembre.",
      translation: "这门课九月开始。",
    },
    {
      word: "nota",
      meaning: "分数；成绩",
      type: "n. f.",
      example: "He sacado una buena nota.",
      translation: "我取得了一个好成绩。",
    },
    {
      word: "aprobar",
      meaning: "通过考试",
      type: "v.",
      example: "Quiero aprobar el examen.",
      translation: "我想通过考试。",
    },
    {
      word: "suspender",
      meaning: "考试不及格",
      type: "v.",
      example: "No quiero suspender la asignatura.",
      translation: "我不想这门课不及格。",
    },
    {
      word: "repasar",
      meaning: "复习",
      type: "v.",
      example: "Necesito repasar antes del examen.",
      translation: "考试前我需要复习。",
    },
    {
      word: "apuntarse",
      meaning: "报名参加",
      type: "v. pron.",
      example: "Me voy a apuntar a un curso de cocina.",
      translation: "我要报名参加一个烹饪课程。",
    },
    {
      word: "asistir",
      meaning: "出席；参加",
      type: "v.",
      example: "Asisto a clase por la tarde.",
      translation: "我下午去上课。",
    },
    {
      word: "faltar",
      meaning: "缺席；缺少",
      type: "v.",
      example: "Hoy falta un estudiante.",
      translation: "今天有一个学生缺席。",
    },
    {
      word: "tarea",
      meaning: "任务；作业",
      type: "n. f.",
      example: "Tengo mucha tarea esta noche.",
      translation: "我今晚有很多作业。",
    },
    {
      word: "biblioteca",
      meaning: "图书馆",
      type: "n. f.",
      example: "Estudio en la biblioteca.",
      translation: "我在图书馆学习。",
    },
    {
      word: "diccionario",
      meaning: "词典",
      type: "n. m.",
      example: "Uso un diccionario para traducir.",
      translation: "我用词典翻译。",
    },
    {
      word: "jefa",
      meaning: "女上司；老板",
      type: "n. f.",
      example: "La jefa habla con el equipo.",
      translation: "女老板和团队说话。",
    },
    {
      word: "compañera",
      meaning: "女同事；同伴",
      type: "n. f.",
      example: "Mi compañera trabaja mucho.",
      translation: "我的女同事工作很努力。",
    },
    {
      word: "sueldo",
      meaning: "工资",
      type: "n. m.",
      example: "El sueldo llega a fin de mes.",
      translation: "工资月底到账。",
    },
    {
      word: "currículum",
      meaning: "简历",
      type: "n. m.",
      example: "Envío mi currículum por correo.",
      translation: "我通过邮件发送简历。",
    },
    {
      word: "gripe",
      meaning: "流感",
      type: "n. f.",
      example: "Tengo gripe y necesito descansar.",
      translation: "我得了流感，需要休息。",
    },
    {
      word: "tos",
      meaning: "咳嗽",
      type: "n. f.",
      example: "Tengo tos desde ayer.",
      translation: "我从昨天开始咳嗽。",
    },
    {
      word: "garganta",
      meaning: "喉咙",
      type: "n. f.",
      example: "Me duele la garganta.",
      translation: "我喉咙痛。",
    },
    {
      word: "pastilla",
      meaning: "药片",
      type: "n. f.",
      example: "Tomo una pastilla después de comer.",
      translation: "我饭后吃一片药。",
    },
    {
      word: "jarabe",
      meaning: "糖浆；止咳糖浆",
      type: "n. m.",
      example: "El médico recomienda un jarabe.",
      translation: "医生推荐一种糖浆。",
    },
    {
      word: "descanso",
      meaning: "休息",
      type: "n. m.",
      example: "Necesito un poco de descanso.",
      translation: "我需要休息一下。",
    },
    {
      word: "peluquería",
      meaning: "理发店",
      type: "n. f.",
      example: "Voy a la peluquería esta tarde.",
      translation: "我今天下午去理发店。",
    },
    {
      word: "cortar",
      meaning: "剪；切",
      type: "v.",
      example: "Quiero cortarme el pelo.",
      translation: "我想剪头发。",
    },
    {
      word: "lavar",
      meaning: "洗",
      type: "v.",
      example: "Voy a lavar la ropa.",
      translation: "我要洗衣服。",
    },
    {
      word: "secar",
      meaning: "弄干；晾干",
      type: "v.",
      example: "Tengo que secar los platos.",
      translation: "我得把盘子擦干。",
    },
    {
      word: "planchar",
      meaning: "熨烫",
      type: "v.",
      example: "Necesito planchar la camisa.",
      translation: "我需要熨衬衫。",
    },
    {
      word: "cuidar",
      meaning: "照顾",
      type: "v.",
      example: "Tengo que cuidar a mi hermano.",
      translation: "我得照顾我弟弟。",
    },
    {
      word: "mascota",
      meaning: "宠物",
      type: "n. f.",
      example: "Mi mascota es un perro pequeño.",
      translation: "我的宠物是一只小狗。",
    },
    {
      word: "pasear",
      meaning: "散步；遛",
      type: "v.",
      example: "Voy a pasear al perro.",
      translation: "我要去遛狗。",
    },
    {
      word: "descargar",
      meaning: "下载",
      type: "v.",
      example: "Voy a descargar la aplicación.",
      translation: "我要下载这个应用。",
    },
    {
      word: "subir",
      meaning: "上传；上去",
      type: "v.",
      example: "Puedes subir la foto a la página.",
      translation: "你可以把照片上传到页面。",
    },
    {
      word: "buscar",
      meaning: "寻找；搜索",
      type: "v.",
      example: "Busco información en internet.",
      translation: "我在网上搜索信息。",
    },
    {
      word: "encontrar",
      meaning: "找到",
      type: "v.",
      example: "No puedo encontrar mi pasaporte.",
      translation: "我找不到我的护照。",
    },
    {
      word: "perder",
      meaning: "丢失；失去",
      type: "v.",
      example: "He perdido las llaves.",
      translation: "我弄丢了钥匙。",
    },
    {
      word: "avisar",
      meaning: "通知；提醒",
      type: "v.",
      example: "Te aviso cuando llegue.",
      translation: "我到了会通知你。",
    },
    {
      word: "mandar",
      meaning: "发送；寄送",
      type: "v.",
      example: "Te mando un mensaje esta tarde.",
      translation: "我今天下午给你发消息。",
    },
    {
      word: "mensaje",
      meaning: "消息；短信",
      type: "n. m.",
      example: "Recibo un mensaje de mi amigo.",
      translation: "我收到朋友的一条消息。",
    },
    {
      word: "aplicación",
      meaning: "应用程序",
      type: "n. f.",
      example: "Esta aplicación es fácil de usar.",
      translation: "这个应用很好用。",
    },
    {
      word: "conectarse",
      meaning: "连接；登录",
      type: "v. pron.",
      example: "Me conecto a internet por la mañana.",
      translation: "我早上连接网络。",
    },
    {
      word: "desconectarse",
      meaning: "断开连接；退出",
      type: "v. pron.",
      example: "Me desconecto después de trabajar.",
      translation: "我工作后退出登录。",
    },
    {
      word: "firma",
      meaning: "签名",
      type: "n. f.",
      example: "Necesito tu firma aquí.",
      translation: "我需要你在这里签名。",
    },
    {
      word: "documento",
      meaning: "文件；证件",
      type: "n. m.",
      example: "Traigo todos los documentos.",
      translation: "我带来了所有文件。",
    },
    {
      word: "formulario",
      meaning: "表格",
      type: "n. m.",
      example: "Hay que completar este formulario.",
      translation: "需要填写这张表格。",
    },
    {
      word: "rellenar",
      meaning: "填写",
      type: "v.",
      example: "Tengo que rellenar el formulario.",
      translation: "我得填写表格。",
    },
    {
      word: "copiar",
      meaning: "复制；抄写",
      type: "v.",
      example: "Puedes copiar la dirección.",
      translation: "你可以复制这个地址。",
    },
    {
      word: "imprimir",
      meaning: "打印",
      type: "v.",
      example: "Necesito imprimir el documento.",
      translation: "我需要打印文件。",
    },
    {
      word: "firmar",
      meaning: "签署",
      type: "v.",
      example: "Voy a firmar el contrato.",
      translation: "我要签合同。",
    },
    {
      word: "solicitar",
      meaning: "申请；请求",
      type: "v.",
      example: "Quiero solicitar información.",
      translation: "我想申请/索取信息。",
    },
    {
      word: "permiso",
      meaning: "许可；准许",
      type: "n. m.",
      example: "Necesito permiso para entrar.",
      translation: "我需要许可才能进入。",
    },
    {
      word: "norma",
      meaning: "规则；规范",
      type: "n. f.",
      example: "Hay que respetar las normas.",
      translation: "必须遵守规则。",
    },
    {
      word: "enlace",
      meaning: "链接",
      type: "n. m.",
      example: "Te mando el enlace por mensaje.",
      translation: "我通过消息把链接发给你。",
    },
    {
      word: "cuenta",
      meaning: "账号；账户",
      type: "n. f.",
      example: "No puedo entrar en mi cuenta.",
      translation: "我无法进入我的账号。",
    },
    {
      word: "página web",
      meaning: "网页；网站",
      type: "n. f.",
      example: "Esta página web es útil.",
      translation: "这个网页很有用。",
    },
    {
      word: "red social",
      meaning: "社交网络",
      type: "n. f.",
      example: "Uso una red social para hablar con amigos.",
      translation: "我用社交网络和朋友聊天。",
    },
    {
      word: "notificación",
      meaning: "通知",
      type: "n. f.",
      example: "Recibo una notificación en el móvil.",
      translation: "我在手机上收到一条通知。",
    },
    {
      word: "actualizar",
      meaning: "更新",
      type: "v.",
      example: "Tengo que actualizar la aplicación.",
      translation: "我需要更新这个应用。",
    },
    {
      word: "accidente",
      meaning: "事故",
      type: "n. m.",
      example: "Hubo un accidente en la carretera.",
      translation: "路上发生了一起事故。",
    },
    {
      word: "carretera",
      meaning: "公路",
      type: "n. f.",
      example: "La carretera está cerrada.",
      translation: "公路关闭了。",
    },
    {
      word: "gasolinera",
      meaning: "加油站",
      type: "n. f.",
      example: "Hay una gasolinera cerca.",
      translation: "附近有一个加油站。",
    },
    {
      word: "garantía",
      meaning: "保修；保证",
      type: "n. f.",
      example: "El producto tiene dos años de garantía.",
      translation: "这个产品有两年保修。",
    },
    {
      word: "queja",
      meaning: "投诉；抱怨",
      type: "n. f.",
      example: "Voy a poner una queja en recepción.",
      translation: "我要在前台投诉。",
    },
  ],

  b1: [
    {
      word: "aunque",
      meaning: "虽然；即使",
      type: "conj.",
      example: "Aunque llueve, voy a salir.",
      translation: "虽然下雨，我还是要出门。",
    },
    {
      word: "sin embargo",
      meaning: "然而；不过",
      type: "loc.",
      example: "Es difícil; sin embargo, quiero intentarlo.",
      translation: "这很难，不过我想试试。",
    },
    {
      word: "por eso",
      meaning: "因此；所以",
      type: "loc.",
      example: "Estoy cansado, por eso voy a descansar.",
      translation: "我很累，所以我要休息。",
    },
    {
      word: "además",
      meaning: "此外；而且",
      type: "adv.",
      example: "Es barato y además está cerca.",
      translation: "它很便宜，而且很近。",
    },
    {
      word: "mientras",
      meaning: "当……时候；与此同时",
      type: "conj.",
      example: "Escucho música mientras estudio.",
      translation: "我学习的时候听音乐。",
    },
    {
      word: "entonces",
      meaning: "那么；于是；当时",
      type: "adv.",
      example: "No tenía dinero, entonces volví a casa.",
      translation: "我没有钱，所以回家了。",
    },
    {
      word: "quizás",
      meaning: "也许；可能",
      type: "adv.",
      example: "Quizás venga mañana.",
      translation: "也许他明天会来。",
    },
    {
      word: "lograr",
      meaning: "实现；达成",
      type: "v.",
      example: "Quiero lograr mi objetivo.",
      translation: "我想实现我的目标。",
    },
    {
      word: "mejorar",
      meaning: "改善；提高",
      type: "v.",
      example: "Necesito mejorar mi español.",
      translation: "我需要提高我的西语。",
    },
    {
      word: "decidir",
      meaning: "决定",
      type: "v.",
      example: "Tengo que decidir hoy.",
      translation: "我今天必须做决定。",
    },
    {
      word: "explicar",
      meaning: "解释",
      type: "v.",
      example: "¿Puedes explicarlo otra vez?",
      translation: "你可以再解释一遍吗？",
    },
    {
      word: "recordar",
      meaning: "记得；回忆",
      type: "v.",
      example: "No puedo recordar su nombre.",
      translation: "我想不起他的名字。",
    },
    {
      word: "olvidar",
      meaning: "忘记",
      type: "v.",
      example: "Olvidé llamar a mi madre.",
      translation: "我忘记给我妈妈打电话了。",
    },
    {
      word: "elegir",
      meaning: "选择",
      type: "v.",
      example: "Es difícil elegir una carrera.",
      translation: "选择一个专业很难。",
    },
    {
      word: "permitir",
      meaning: "允许",
      type: "v.",
      example: "El profesor no permite usar el móvil.",
      translation: "老师不允许使用手机。",
    },
    {
      word: "continuar",
      meaning: "继续",
      type: "v.",
      example: "Quiero continuar mis estudios.",
      translation: "我想继续我的学习。",
    },
    {
      word: "conseguir",
      meaning: "得到；实现",
      type: "v.",
      example: "Conseguí un nuevo trabajo.",
      translation: "我找到了一份新工作。",
    },
    {
      word: "cambiar",
      meaning: "改变；更换",
      type: "v.",
      example: "Quiero cambiar mi forma de estudiar.",
      translation: "我想改变我的学习方式。",
    },
    {
      word: "desarrollar",
      meaning: "发展；培养",
      type: "v.",
      example: "Es importante desarrollar buenos hábitos.",
      translation: "培养好习惯很重要。",
    },
    {
      word: "descubrir",
      meaning: "发现",
      type: "v.",
      example: "Descubrí una ciudad muy bonita.",
      translation: "我发现了一座美丽的城市。",
    },
    {
      word: "organizar",
      meaning: "组织；安排",
      type: "v.",
      example: "Necesito organizar mejor mi tiempo.",
      translation: "我需要更好地安排时间。",
    },
    {
      word: "ofrecer",
      meaning: "提供",
      type: "v.",
      example: "La empresa ofrece cursos gratuitos.",
      translation: "公司提供免费课程。",
    },
    {
      word: "pedir",
      meaning: "请求；点餐；要",
      type: "v.",
      example: "Voy a pedir ayuda.",
      translation: "我要请求帮助。",
    },
    {
      word: "aceptar",
      meaning: "接受",
      type: "v.",
      example: "Acepté la invitación.",
      translation: "我接受了邀请。",
    },
    {
      word: "rechazar",
      meaning: "拒绝",
      type: "v.",
      example: "Tuve que rechazar la oferta.",
      translation: "我不得不拒绝这个提议。",
    },
    {
      word: "darse cuenta",
      meaning: "意识到；察觉",
      type: "v. pron.",
      example: "Me di cuenta de mi error.",
      translation: "我意识到了我的错误。",
    },
    {
      word: "costumbre",
      meaning: "习惯；风俗",
      type: "n. f.",
      example: "Es una costumbre muy antigua.",
      translation: "这是一个很古老的习俗。",
    },
    {
      word: "consejo",
      meaning: "建议",
      type: "n. m.",
      example: "Gracias por tu consejo.",
      translation: "谢谢你的建议。",
    },
    {
      word: "cambio",
      meaning: "变化；改变",
      type: "n. m.",
      example: "Este cambio es importante.",
      translation: "这个变化很重要。",
    },
    {
      word: "éxito",
      meaning: "成功",
      type: "n. m.",
      example: "El éxito requiere paciencia.",
      translation: "成功需要耐心。",
    },
    {
      word: "fracaso",
      meaning: "失败",
      type: "n. m.",
      example: "El fracaso también enseña.",
      translation: "失败也会教会人东西。",
    },
    {
      word: "desarrollo",
      meaning: "发展",
      type: "n. m.",
      example: "El desarrollo personal es importante.",
      translation: "个人发展很重要。",
    },
    {
      word: "relación",
      meaning: "关系",
      type: "n. f.",
      example: "Tenemos una buena relación.",
      translation: "我们关系很好。",
    },
    {
      word: "experiencia",
      meaning: "经验；经历",
      type: "n. f.",
      example: "Fue una experiencia interesante.",
      translation: "那是一次有趣的经历。",
    },
    {
      word: "oportunidad",
      meaning: "机会",
      type: "n. f.",
      example: "Es una buena oportunidad para aprender.",
      translation: "这是一个学习的好机会。",
    },
    {
      word: "problema",
      meaning: "问题",
      type: "n. m.",
      example: "Tenemos que resolver este problema.",
      translation: "我们必须解决这个问题。",
    },
    {
      word: "solución",
      meaning: "解决办法",
      type: "n. f.",
      example: "Necesitamos encontrar una solución.",
      translation: "我们需要找到一个解决办法。",
    },
    {
      word: "ventaja",
      meaning: "优势；好处",
      type: "n. f.",
      example: "Una ventaja de vivir aquí es el transporte.",
      translation: "住在这里的一个好处是交通方便。",
    },
    {
      word: "desventaja",
      meaning: "劣势；缺点",
      type: "n. f.",
      example: "La desventaja es el precio.",
      translation: "缺点是价格。",
    },
    {
      word: "opinión",
      meaning: "观点；意见",
      type: "n. f.",
      example: "En mi opinión, es una buena idea.",
      translation: "在我看来，这是个好主意。",
    },
    {
      word: "acuerdo",
      meaning: "协议；一致",
      type: "n. m.",
      example: "Estoy de acuerdo contigo.",
      translation: "我同意你的看法。",
    },
    {
      word: "desacuerdo",
      meaning: "不同意；分歧",
      type: "n. m.",
      example: "Hay un desacuerdo entre ellos.",
      translation: "他们之间有分歧。",
    },
    {
      word: "motivo",
      meaning: "原因；理由",
      type: "n. m.",
      example: "No entiendo el motivo.",
      translation: "我不明白原因。",
    },
    {
      word: "causa",
      meaning: "原因；起因",
      type: "n. f.",
      example: "La causa del problema no está clara.",
      translation: "问题的原因还不清楚。",
    },
    {
      word: "consecuencia",
      meaning: "后果；结果",
      type: "n. f.",
      example: "Cada decisión tiene consecuencias.",
      translation: "每个决定都有后果。",
    },
    {
      word: "objetivo",
      meaning: "目标",
      type: "n. m.",
      example: "Mi objetivo es hablar mejor.",
      translation: "我的目标是说得更好。",
    },
    {
      word: "esfuerzo",
      meaning: "努力",
      type: "n. m.",
      example: "El esfuerzo vale la pena.",
      translation: "努力是值得的。",
    },
    {
      word: "nivel",
      meaning: "水平；等级",
      type: "n. m.",
      example: "Mi nivel de español es B1.",
      translation: "我的西语水平是 B1。",
    },
    {
      word: "sociedad",
      meaning: "社会",
      type: "n. f.",
      example: "La sociedad cambia rápidamente.",
      translation: "社会变化很快。",
    },
    {
      word: "cultura",
      meaning: "文化",
      type: "n. f.",
      example: "Me interesa la cultura española.",
      translation: "我对西班牙文化感兴趣。",
    },
    {
      word: "comunicación",
      meaning: "交流；沟通",
      type: "n. f.",
      example: "La comunicación es fundamental.",
      translation: "沟通是很重要的。",
    },
    {
      word: "información",
      meaning: "信息",
      type: "n. f.",
      example: "Necesito más información.",
      translation: "我需要更多信息。",
    },
    {
      word: "noticia",
      meaning: "新闻；消息",
      type: "n. f.",
      example: "Leí una noticia interesante.",
      translation: "我读到了一条有趣的新闻。",
    },
    {
      word: "medio ambiente",
      meaning: "环境",
      type: "n. m.",
      example: "Debemos proteger el medio ambiente.",
      translation: "我们应该保护环境。",
    },
    {
      word: "contaminación",
      meaning: "污染",
      type: "n. f.",
      example: "La contaminación afecta a la salud.",
      translation: "污染影响健康。",
    },
    {
      word: "energía",
      meaning: "能源；精力",
      type: "n. f.",
      example: "Necesitamos usar menos energía.",
      translation: "我们需要少用能源。",
    },
    {
      word: "naturaleza",
      meaning: "自然；大自然",
      type: "n. f.",
      example: "Me gusta pasar tiempo en la naturaleza.",
      translation: "我喜欢在大自然中度过时间。",
    },
    {
      word: "recurso",
      meaning: "资源",
      type: "n. m.",
      example: "El agua es un recurso importante.",
      translation: "水是一种重要资源。",
    },
    {
      word: "salud",
      meaning: "健康",
      type: "n. f.",
      example: "La salud es más importante que el dinero.",
      translation: "健康比钱更重要。",
    },
    {
      word: "enfermedad",
      meaning: "疾病",
      type: "n. f.",
      example: "Esta enfermedad es común en invierno.",
      translation: "这种疾病在冬天很常见。",
    },
    {
      word: "tratamiento",
      meaning: "治疗",
      type: "n. m.",
      example: "El tratamiento dura dos semanas.",
      translation: "治疗持续两周。",
    },
    {
      word: "síntoma",
      meaning: "症状",
      type: "n. m.",
      example: "La fiebre es un síntoma frecuente.",
      translation: "发烧是一个常见症状。",
    },
    {
      word: "estrés",
      meaning: "压力",
      type: "n. m.",
      example: "El estrés puede afectar al sueño.",
      translation: "压力会影响睡眠。",
    },
    {
      word: "bienestar",
      meaning: "幸福；身心健康",
      type: "n. m.",
      example: "El bienestar mental es importante.",
      translation: "心理健康很重要。",
    },
    {
      word: "educación",
      meaning: "教育",
      type: "n. f.",
      example: "La educación abre muchas puertas.",
      translation: "教育打开很多机会之门。",
    },
    {
      word: "universidad",
      meaning: "大学",
      type: "n. f.",
      example: "Estudio en la universidad.",
      translation: "我在大学学习。",
    },
    {
      word: "asignatura",
      meaning: "科目；课程",
      type: "n. f.",
      example: "Mi asignatura favorita es historia.",
      translation: "我最喜欢的科目是历史。",
    },
    {
      word: "examen",
      meaning: "考试",
      type: "n. m.",
      example: "Tengo un examen la próxima semana.",
      translation: "我下周有一场考试。",
    },
    {
      word: "resultado",
      meaning: "结果；成绩",
      type: "n. m.",
      example: "Estoy esperando el resultado.",
      translation: "我正在等待结果。",
    },
    {
      word: "empleo",
      meaning: "工作；就业",
      type: "n. m.",
      example: "Busco empleo en Madrid.",
      translation: "我在马德里找工作。",
    },
    {
      word: "entrevista",
      meaning: "面试；采访",
      type: "n. f.",
      example: "Tengo una entrevista mañana.",
      translation: "我明天有一个面试。",
    },
    {
      word: "salario",
      meaning: "工资；薪水",
      type: "n. m.",
      example: "El salario es suficiente para vivir.",
      translation: "这份工资足够生活。",
    },
    {
      word: "contrato",
      meaning: "合同",
      type: "n. m.",
      example: "Firmé un contrato nuevo.",
      translation: "我签了一份新合同。",
    },
    {
      word: "habilidad",
      meaning: "能力；技能",
      type: "n. f.",
      example: "Hablar idiomas es una habilidad útil.",
      translation: "会说外语是一项有用的技能。",
    },
    {
      word: "responsabilidad",
      meaning: "责任",
      type: "n. f.",
      example: "Es una gran responsabilidad.",
      translation: "这是一个很大的责任。",
    },
    {
      word: "independiente",
      meaning: "独立的",
      type: "adj.",
      example: "Quiero ser más independiente.",
      translation: "我想变得更独立。",
    },
    {
      word: "necesario",
      meaning: "必要的",
      type: "adj.",
      example: "Es necesario practicar cada día.",
      translation: "每天练习是必要的。",
    },
    {
      word: "posible",
      meaning: "可能的",
      type: "adj.",
      example: "Es posible aprender con constancia.",
      translation: "坚持学习是可以学会的。",
    },
    {
      word: "probable",
      meaning: "可能的；大概的",
      type: "adj.",
      example: "Es probable que llegue tarde.",
      translation: "他可能会迟到。",
    },
    {
      word: "seguro",
      meaning: "安全的；确定的",
      type: "adj.",
      example: "Estoy seguro de mi respuesta.",
      translation: "我确定我的答案。",
    },
    {
      word: "útil",
      meaning: "有用的",
      type: "adj.",
      example: "Este consejo es muy útil.",
      translation: "这个建议很有用。",
    },
    {
      word: "común",
      meaning: "常见的；共同的",
      type: "adj.",
      example: "Es un error común.",
      translation: "这是一个常见错误。",
    },
  ],
  b2: toWordItems(b2Words),
  c1: toWordItems(c1Words)
};